author: 'Figali Taho'
defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      layout: 'base'
description: "I’m Figali Taho."
exclude:
  - '.gitignore'
  - 'CNAME'
  - 'LICENSE'
  - 'README.md'
  - 'sketch'
keywords: 'code, design, startups, technology, tech, design'
permalink: pretty
sass:
  style: compressed
  sass_dir: 'assets/styles'
timezone: America/New_York
title: Figali Taho
url: "https://meagher.co"
